spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${TRIPHUB_DB_URL}
    username: ${TRIPHUB_DB_USERNAME}
    password: ${TRIPHUB_DB_PASSWORD}

  redis:
    host: ${TRIPHUB_REDIS_HOST}
    port: ${TRIPHUB_REDIS_PORT:6379}
